### ISSUE TITLE
Server crash on joining carts

### ISSUE THREAD

**Issue by Cervator** [Terasology/Rails#39]
During a play test

```
14:04:29.701 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 1813470, netId = 685, prefab = 'Rails:rail'}
14:04:29.701 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 1813470, netId = 685, prefab = 'Rails:rail'}
14:04:29.701 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 1813470, netId = 685, prefab = 'Rails:rail'}
14:04:29.701 [main] INFO  o.t.n.internal.NetworkSystemImpl - Component class org.terasology.entitySystem.entity.internal.EntityInfoComponent added to EntityRef{id = 1813470, netId = 685, prefab = 'Rails:rail'}
14:04:29.810 [main] INFO  o.t.m.controllers.CartJointSystem - Joint created between: EntityRef{id = 676868, netId = 508, prefab = 'Rails:minecartVehicle'} and EntityRef{id = 676868, netId = 508, prefab = 'Rails:minecartVehicle'}
14:04:29.815 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
	at org.terasology.minecarts.controllers.CartJointSystem.applyImpulseOnSocket(CartJointSystem.java:118)
	at org.terasology.minecarts.controllers.CartJointSystem.update(CartJointSystem.java:105)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:175)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:437)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:400)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:376)
	at org.terasology.engine.Terasology.main(Terasology.java:143)
14:04:29.815 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
14:04:30.084 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Creating game snapshot
14:04:30.087 [main] INFO  o.t.p.i.ReadWriteStorageManager - Saving - Snapshot created: Writing phase starts
14:04:30.199 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Cervator861
14:04:30.201 [main] INFO  o.t.n.internal.NetworkSystemImpl - Client disconnected: Pparter
```

**Comment by pollend** [comment]
occurs when two carts are joined.
